# This will be the first part of the title tag for your site <title> site.name + page.title </title>
title: Future Gadget Collectibles
url: "https://www.futuregadgetlabs.com" # the base hostname & protocol for your site, e.g. http://example.com, also used in jekyll-seo-tag
baseurl: /Store
repo: https://github.com/YJPL/Supply/
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
tagline:
description: Jekyll template for e-commerce with Stripe integration
author:
  name: Future Gadget Collectibles
  email:
  twitter: TemplatesSupply # twitter username without the @ symbol
  phone: ""
social:
  name: Templates Supply # replace this
  links:
    - https://github.com/YJPL/supply
    - https://www.linkedin.com/company/templates-supply/

# Build settings
markdown: kramdown
timezone: America/New_York

collections:
  products:
    _hide_content: false
    output: true

permalink: /:title/ # pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-leaflet
  - jekyll-feed
  - jekyll-archives # not on Supply theme

include:
  - .htaccess
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENCE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Stripe settings
stripe:
  mode: test  # 'live' or 'test'
  publishable_key_live: pk_live_51SrO2CLuNRMBM7fJQ8gB5uTyU88mOe9GGD42RavoBoPKCedjluc1tnkUO8f2QH17iv2nUjf24Pv4Jkaophud5Msn00GIJHsgrc
  publishable_key_test: pk_test_51SrO2KLTedha2xGONS9gH7fveAobQdtlC7a5ulXDOJEKQR5rTjARXicnFPc31EzFDwbF994rbtw4RJtYXZ4tl0j500JOwngouM
  checkout_url_live: https://stripecheckoutsessionlive.netlify.app/.netlify/functions/create-checkout-session
  checkout_url_test: https://stripecheckoutsessiontest.netlify.app/.netlify/functions/create-checkout-session

# Contact settings
formcarry: https://formcarry.com/ # add you formcarry endpoint url (see https://formcarry.com/documentation/getting-started)

# Social

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

feed:
  collections:
    products:
      path: "/products.xml"

# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: 'all'
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'
  category_archive:
    type: liquid
